Update transform.py because of RuntimeError
Got
RuntimeError: dictionary changed size during iteration
on locals iteration, because locals, change when you iter over them,